// src/components/views/elements/ElementTile.tsx
import {ElementModel} from "../../../models/element.model";
import {hasPoint} from "../../../utils/element.util";
import {TileStateModel} from "../../../models/tile-state.model";
import {getBlockUrl} from "../../../utils/render.util";

interface ElementTileProps {
    element: ElementModel;
    x: number;
    y: number;
    colorSchemeIndex: number;
}

export default function ({
    element,
    x,
    y,
    colorSchemeIndex,
}: ElementTileProps) {
    const exists = hasPoint(element, x, y);
    const url = getBlockUrl(TileStateModel.BLOCKED, colorSchemeIndex, element.colors);

    return (
        <div className="col-auto tile-frames">
            {exists && (
                <div v-if="exists" className="tile">
                    <img src={url} className="tile-background-image" loading="lazy"/>
                </div>
            )}
        </div>
    )
}

// src/components/views/elements/ElementTile.vue
<script setup lang="ts">
import {computed} from "vue";
import {ElementModel} from "../../../models/element.model";
import {hasPoint} from "../../../utils/element.util";
import {TileStateModel} from "../../../models/tile-state.model";
import {getBlockUrl} from "../../../utils/render.util";

interface ElementProps {
  element: ElementModel;
  x: number;
  y: number;
  colorSchemeIndex: number;
}

const props = defineProps<ElementProps>();

const exists = computed(() => hasPoint(props.element, props.x, props.y));
const url = computed(() =>
    getBlockUrl(TileStateModel.BLOCKED, props.colorSchemeIndex, props.element.colors));
</script>

<template>
  <div class="col-auto tile-frames">
    <div v-if="exists" class="tile">
      <img :src="url" class="tile-background-image" loading="lazy">
    </div>
  </div>
</template>
