// src/components/views/grid/GridContent.tsx
import GridTile from "./GridTile";
import {useAppContext} from "../../contexts/AppContext";

export default function () {
    const {
        gameState,
    } = useAppContext();

    const grid = gameState.grid;
    const themeIndex = gameState.colorIndex;

    return (
        <>
            {grid && Array.from({ length: grid.yLength }, (_, y) => (
                <div key={y} className="row g-0 justify-content-center">
                    {Array.from({ length: grid.xLength }, (_, x) => (
                        <GridTile
                            key={`${x}-${y}`}
                            x={x}
                            y={y}
                            colorSchemeIndex={themeIndex}
                            grid={grid}
                        />
                    ))}
                </div>
            ))}
        </>
    )
}

// src/components/views/grid/GridContent.vue
<script setup lang="ts">
import {injectAppContext} from "../../../contexts/app.context";
import {computed} from "vue";
import GridTile from "./GridTile.vue";

const app = injectAppContext();

const grid = computed(() => app.gameState.value.grid);
const themeIndex = computed(() => app.gameState.value.colorIndex);

</script>
<template>
  <div
      v-if="grid"
      v-for="y in grid.yLength"
      class="row g-0 justify-content-center"
  >
    <GridTile
        v-for="x in grid.xLength"
        :x="x - 1"
        :y="y - 1"
        :key="x + '-' + y"
        :color-scheme-index="themeIndex"
        :grid="grid"
    />
  </div>
</template>
