// src/components/views/grid/GridTile.vue
<script setup lang="ts">
import {gridTileInfo, GridTileProps} from "../../../composables/useGridTile";

const props = defineProps<GridTileProps>();

const tileInfo = gridTileInfo(props);

</script>

<template>
  <div class="col-auto">
    <div class="tile main-tile" v-bind:data-index="tileInfo.index">
      <img v-bind:src="tileInfo.url" class="tile-background-image" loading="lazy">
    </div>
  </div>
</template>

// src/components/views/grid/GridTile.tsx
import {getTile} from "../../../utils/tile.util";
import {getBlockUrl} from "../../../utils/render.util";
import {GridModel} from "../../../models/grid.model";

interface GridTileProps {
    x: number;
    y: number;
    grid: GridModel;
    colorSchemeIndex: number;
}

export default function ({
    x,
    y,
    grid,
    colorSchemeIndex,
}: GridTileProps) {
    const tile = getTile(grid, x, y);

    const url = getBlockUrl(tile.state.state, colorSchemeIndex, tile.colors);
    const index = tile.index;

    return (
        <div className="col-auto">
            <div className="tile main-tile" data-index={index}>
                <img src={url} className="tile-background-image" loading="lazy" />
            </div>
        </div>
    )
}
