// src/components/views/settings/Settings.vue
<script setup lang="ts">
import { ref } from 'vue';
import { setColor } from '../../../services/settings.service';
import { injectAppContext } from '../../../contexts/app.context';

const app = injectAppContext();
const dialog = ref(false);
const activeTab = ref(0);

const handleThemeClick = (index: number) => {
  setColor(index);
  app.gameState.value.colorIndex = index;
};
</script>

<template>
  <!-- Settings Button -->
  <v-btn icon color="primary" @click="dialog = true">
    <v-icon>mdi-cog</v-icon>
  </v-btn>

  <!-- Settings Modal -->
  <v-dialog v-model="dialog" max-width="600">
    <v-card>
      <v-card-title class="text-h6">
        Settings
        <v-spacer></v-spacer>
        <v-btn icon @click="dialog = false">
          <v-icon>mdi-close</v-icon>
        </v-btn>
      </v-card-title>

      <v-card-text>
        <v-tabs v-model="activeTab" background-color="transparent" grow>
          <v-tab>Game</v-tab>
          <v-tab>About</v-tab>
        </v-tabs>

        <v-tabs-items v-model="activeTab">
          <!-- Game Tab -->
          <v-tab-item>
            <p class="sub-title">Multiplayer</p>
            <v-btn color="primary" class="mb-2">Copy Link</v-btn>

            <p class="sub-title">Color Settings</p>
            <v-menu>
              <template #activator="{ props }">
                <v-btn v-bind="props" color="primary" outlined>
                  Change Color Scheme
                  <v-icon right>mdi-menu-down</v-icon>
                </v-btn>
              </template>
              <v-list>
                <v-list-item @click="handleThemeClick(1)">
                  <v-list-item-title>Aquatic</v-list-item-title>
                </v-list-item>
                <v-list-item @click="handleThemeClick(2)">
                  <v-list-item-title>Tropical</v-list-item-title>
                </v-list-item>
                <v-list-item @click="handleThemeClick(3)">
                  <v-list-item-title>Hellfire</v-list-item-title>
                </v-list-item>
                <v-list-item @click="handleThemeClick(0)">
                  <v-list-item-title>Retro</v-list-item-title>
                </v-list-item>
              </v-list>
            </v-menu>

            <p class="sub-title">Save and Load</p>
            <v-btn color="primary" class="me-2">Save Game</v-btn>
            <v-btn color="primary" outlined>
              Upload Game
              <input type="file" style="display:none;" />
            </v-btn>
          </v-tab-item>

          <!-- About Tab -->
          <v-tab-item>
            <p class="sub-title">About</p>
            <p>
              This is a clone of the mobile game
              <a href="https://apps.apple.com/de/app/blockudoku-block-puzzle/id1452227871?l=en-GB" target="_blank">
                Blockudoku
              </a> written in Scala by Florian Dritter and Tom Berger.
              <br />
              This project is an academic project at HTWG Konstanz.
            </p>
          </v-tab-item>
        </v-tabs-items>
      </v-card-text>

      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn color="primary" @click="dialog = false">Close</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

// src/components/views/settings/Settings.tsx
import {MouseEventHandler, useState} from "react";
import {
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
    Button,
    Tabs,
    Tab,
    Menu,
    MenuItem,
    Card,
    CardContent,
    IconButton,
} from "@mui/material";
import SettingsIcon from "@mui/icons-material/Settings";
import {useAppContext} from "../../contexts/AppContext";

export default function() {
    const {
        updateTheme
    } = useAppContext();

    const [dialog, setDialog] = useState(false);
    const [activeTab, setActiveTab] = useState(0);
    const [menuAnchor, setMenuAnchor] = useState<Element | null>(null);

    const openMenu: MouseEventHandler<HTMLButtonElement> = (e) => setMenuAnchor(e.currentTarget);
    const closeMenu = () => setMenuAnchor(null);

    const handleThemeClick = (index: number) => {
        updateTheme(index);
        closeMenu();
    };

    return (
        <>
            <IconButton onClick={() => setDialog(true)} sx={{ color: "#0099cc", position: 'absolute', bottom: 20, right: 20 }}>
                <SettingsIcon fontSize="large" />
            </IconButton>

            <Dialog open={dialog} onClose={() => setDialog(false)} maxWidth="sm" fullWidth>
                <Card sx={{ background: "#2a2a4a" }}>
                    <DialogTitle sx={{ color: "white" }}>Settings</DialogTitle>

                    <DialogContent>
                        <Tabs
                            value={activeTab}
                            onChange={(_, v) => setActiveTab(v)}
                            textColor="inherit"
                            indicatorColor="primary"
                        >
                            <Tab label="Game" sx={{ color: "white" }} />
                            <Tab label="About" sx={{ color: "white" }} />
                        </Tabs>

                        {activeTab === 0 && (
                            <CardContent sx={{ color: "white" }}>
                                <p>Multiplayer</p>
                                <Button variant="contained" sx={{ mb: 2, background: "#0099cc" }}>
                                    Copy Link
                                </Button>

                                <p>Color Settings</p>
                                <Button
                                    variant="contained"
                                    sx={{ mb: 2, background: "#0099cc" }}
                                    onClick={openMenu}
                                >
                                    Change Color Scheme
                                </Button>

                                <Menu anchorEl={menuAnchor} open={Boolean(menuAnchor)} onClose={closeMenu}>
                                    <MenuItem onClick={() => handleThemeClick(1)}>Aquatic</MenuItem>
                                    <MenuItem onClick={() => handleThemeClick(2)}>Tropical</MenuItem>
                                    <MenuItem onClick={() => handleThemeClick(3)}>Hellfire</MenuItem>
                                    <MenuItem onClick={() => handleThemeClick(0)}>Retro</MenuItem>
                                </Menu>

                                <p>Save and Load</p>
                                <Button variant="contained" sx={{ mr: 2, background: "#0099cc" }}>
                                    Save Game
                                </Button>

                                <Button variant="outlined" component="label" sx={{ borderColor: "#0099cc", color: "#0099cc" }}>
                                    Upload Game
                                    <input type="file" hidden />
                                </Button>
                            </CardContent>
                        )}

                        {activeTab === 1 && (
                            <CardContent sx={{ color: "white" }}>
                                <p>About</p>
                                <p>
                                    This is a clone of the mobile game
                                    <a
                                        href="https://apps.apple.com/de/app/blockudoku-block-puzzle/id1452227871?l=en-GB"
                                        target="_blank"
                                        rel="noreferrer"
                                        style={{ color: "#0099cc" }}
                                    >
                                        Blockudoku
                                    </a>
                                    written in Scala. This project is an academic project at HTWG Konstanz.
                                </p>
                            </CardContent>
                        )}
                    </DialogContent>

                    <DialogActions>
                        <Button sx={{ color: "#0099cc" }} onClick={() => setDialog(false)}>
                            Close
                        </Button>
                    </DialogActions>
                </Card>
            </Dialog>
        </>
    );
}
